### ISSUE TITLE
CI: Get correct branch name for the test

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#263]
When I was making a PR for 2.2.18 release, the CI didn't get green because it tries to pull master branch for testing.

```yaml
      - name: Checkout dm-writeboost
        uses: actions/checkout@v4
        with:
          repository: akiradeveloper/dm-writeboost
          ref: master
          path: module
```

This should behave in this way.

1. Pull the branch in PR when in pull request.
2. Pull the master when merged.
